//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientsApp.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Device
    {
        public int ID { get; set; }
        public string deviceType { get; set; }
        public string deviceModel { get; set; }
        public Nullable<int> deviceGrade { get; set; }
       

    }
   

}
